os: linux

services:
  - docker

env: DATED=$(date +%Y%m%d)

script: >
  docker build -t wloot/ss-docker:latest -t wloot/ss-docker:$DATED . &&
  docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" &&
  docker push wloot/ss-docker:latest &&
  docker push wloot/ss-docker:$DATED
