os: linux

services:
  - docker

script:
  - docker build -t wloot/ss-docker:test .
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker push wloot/ss-docker:test
